export const apis = {
  login: "/public/user/login",
  get_all_users: "/resources/user/get_users",
  add_new_user: "/resources/user/add_user",
  update_user: "/resources/user/edit_user",
  get_all_courses: "/public/course/get_courses",
  add_new_course: "/resources/course/add_course",
  update_course: "/resources/course/edit_course",
  get_all_lessons: "/resources/lesson/get_lessons",
  get_all_tests: "/resources/test/get_tests",
  add_new_test: "/resources/test/add_test",
  update_test: "/resources/test/edit_test",
  get_all_questions: "/resources/question/get_questions",
  get_all_books: "/public/book/get_books",
  add_book: "/resources/book/add_book",
  edit_book: "/resources/book/edit_book",
  delete_book: "/resources/book/delete_book",
  get_all_audios: "/public/audio/get_audios",
  add_audio: "/resources/audio/add_audio",
  edit_audio: "/resources/audio/edit_audio",
  delete_audio: "/resources/audio/delete_audio",
  get_test_history: "/resources/test_history/get_test_history",
};
